#!/bin/bash

# AppImage entry point for ShieldPrompt

# Get the directory where this AppImage is located
HERE="$(dirname "$(readlink -f "${0}")")"

# Set up environment
export PATH="${HERE}/usr/bin:${PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"

# Launch the application
exec "${HERE}/usr/bin/ShieldPrompt" "$@"

