namespace ShieldPrompt.Domain.ValueObjects;

/// <summary>
/// Represents a count of tokens in content.
/// Immutable value object.
/// </summary>
public readonly record struct TokenCount : IComparable<TokenCount>
{
    public TokenCount(int count)
    {
        if (count < 0)
            throw new ArgumentException("Token count cannot be negative.", nameof(count));

        Count = count;
    }

    /// <summary>
    /// The number of tokens.
    /// </summary>
    public int Count { get; }

    /// <summary>
    /// Adds two token counts together.
    /// </summary>
    public TokenCount Add(TokenCount other) => new(Count + other.Count);

    /// <summary>
    /// Compares this token count to another.
    /// </summary>
    public int CompareTo(TokenCount other) => Count.CompareTo(other.Count);

    /// <summary>
    /// Returns the count as a string.
    /// </summary>
    public override string ToString() => Count.ToString();

    // Equality and operators are automatically generated by record struct
}

